/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportRouteImport } from './routes/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/graph': typeof GraphRoute
  '/heatmap': typeof HeatmapRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/graph': typeof GraphRoute
  '/heatmap': typeof HeatmapRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/graph': typeof GraphRoute
  '/heatmap': typeof HeatmapRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/graph'
    | '/heatmap'
    | '/locker'
    | '/login'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/graph'
    | '/heatmap'
    | '/locker'
    | '/login'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/graph'
    | '/heatmap'
    | '/locker'
    | '/login'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  GraphRoute: typeof GraphRoute
  HeatmapRoute: typeof HeatmapRoute
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  GraphRoute: GraphRoute,
  HeatmapRoute: HeatmapRoute,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
